### PR TITLE
Subscriptions

### PR DESCRIPTION
**Pull request by rlingineni**
I’m not exactly sure what to do when a change occurs, it currently just
prints to console if a change happens. 

Doorbell is very slow (maybe my internet connection, it’s slow with the Ring App too)

Checking in initial set of commits.

### CODE REVIEW

**Comment by rlingineni** [comment]
Maybe there can just be a `subscribeForStateChange()` in the schemas so it's clear they can subscribe to something. They should implement their own custom callback.

**Comment by jasongin** [comment]
In the updated translator interface design I'm working on, any property can have the ability to notify of state changes. In the current format, those can be mapped to signals.

So I wouldn't worry about this right now; we'll update translators later for the new design.

**Comment by tjaffri** [comment]
I'll take a look and merge. Sorry about the delay.

**Comment by tjaffri** [comment]
just wanted to explain the delay in merging this one... in the dev branch, you will notice significant changes to our directory structure etc... specifically see #53.

Once we are done with those, we will likely need to rebase this PR to the new dir structure and package format. So please hang tight till then, and we will figure out how to merge this one.

**Comment by arjun-msft** [comment]
Closing this out as we are leveraging PubSubHubBub for notifications.

**Pull request closed without merging**
