### PR TITLE
SmartThings - support multiple hubs

### PR DESCRIPTION
**Pull request by m-chau**
A fix for Issue #191.
Passed all unit tests for SmartThings translators.

### CODE REVIEW

**Comment by arjun-msft** [comment]
>     }

don't you need to update the devicedata.json?

---
Refers to: org.opent2t.sample.hub.superpopular/com.smartthings.hub/test/mockSmartthingsHub.js:10 in a661b07. [](commit_id = a661b07b2aa8ee5a9741fde58f6aaacb08193074, deletion_comment = False)

**Comment by arjun-msft** [comment]
:shipit:

**Comment by m-chau** [comment]
>     }

do you mean to update it with more then one hub?

---
In reply to: [285834567](https://github.com/openT2T/translators/pull/200#issuecomment-285834567) [](ancestors = 285834567)

---
Refers to: org.opent2t.sample.hub.superpopular/com.smartthings.hub/test/mockSmartthingsHub.js:10 in a661b07. [](commit_id = a661b07b2aa8ee5a9741fde58f6aaacb08193074, deletion_comment = False)

**Comment by arjun-msft** [comment]
>     }

yes

---
In reply to: [286004815](https://github.com/openT2T/translators/pull/200#issuecomment-286004815) [](ancestors = 286004815,285834567)

---
Refers to: org.opent2t.sample.hub.superpopular/com.smartthings.hub/test/mockSmartthingsHub.js:10 in a661b07. [](commit_id = a661b07b2aa8ee5a9741fde58f6aaacb08193074, deletion_comment = False)

**Comment by danielrischar** [comment]
:shipit:

**Pull request merged**
