### PR TITLE
Large dir structure changes, resolving #24 and #43

### PR DESCRIPTION
**Pull request by tjaffri**
@jeanpa @jasongin this is the first wave of repo dir structure changes we discussed. Would like feedback from everyone as well... @arjun-msft please check it out especially.

I will add on to this PR with the fixes for #44 and #46 but wanted to get some eyeballs on the changes as I go.

It is hard to view all these changes as a diff. All I can say is the changes are only moving things around... nothing functional changed. I tried to check to make sure I didn't miss anything but can fix in subsequent PRs if anything else needs to be updated.

Since this is a pretty large disruptive change I'd like to get this merged ASAP so we can review other changes to follo more easily and also start on fixing everything else that will break with these fixes (e.g. anything that depends on the repo structure, e.g. some of the sample apps)

### CODE REVIEW

**Comment by jasongin** [comment]
I agree with Sanjai's comment (in email) that the reverse-dns names should be all lowercase.

**Comment by jasongin** [comment]
What is the reason for switching the order of the schema name components, from "org.opent2t.superpopular.thermostat" to "org.opent2t.thermostat.superpopular.sample"?

Also I don't understand why we need both "superpopular" and "sample" in the names. So I would suggest names like "org.opent2t.sample.thermostat".

**Comment by jasongin** [comment]
:clock1:

**Comment by tjaffri** [comment]
@jasongin and @sanjaiganesh I discussed with @jeanpa about both of these, and they are #ByDesign. Specifically:

1. Switching the name of the schema name components from "org.opent2t.superpopular.thermostat" to "org.opent2t.thermostat.superpopular.sample" is for readability on GitHub... so we can actually read what translator is what when you go to the repo home on GitHub.

2. The capitalization is also something we have done since the beginning (see original schema names). We can certainly reconsider going forward, but for now not changing that pre-exisiting convention.

**Comment by tjaffri** [comment]
Also, @jeanpa gave a verbal :shipit: so merging on his behalf

**Pull request merged**
